### ISSUE TITLE
Missing bbox and frames 

### ISSUE THREAD

**Issue by lan786** [mkocabas/VIBE#37]
Hi @mkocabas , In this issue #27 as I mentioned that I tested this project in two different PC, in first PC  rendering is not working both with osmesa and egl. 
And in second PC, there is no any problem with Pyrender and rendering is working but no 3D predictions because model is saving empty pkl file. 
I figured out this problem and I came to know that problem starts from [demo.py line 83](https://github.com/mkocabas/VIBE/blob/master/demo.py#L83).  In tracking_results (pointing to [run_posetracker](https://github.com/mkocabas/VIBE/blob/master/lib/utils/pose_tracker.py#L80)) there are arrays of bbox and frames but in my case (in second PC) tracking_results is empty dict. 
In [run_posetracker](https://github.com/mkocabas/VIBE/blob/master/lib/utils/pose_tracker.py#L80) there is "video_file", "staf_folder", and "posetrack_output_folder". For "staf_folder" is it mandatory to install [OpenPose STAF](https://github.com/soulslicer/openpose/tree/staf) and set the directory as in current situation it is pointed to your directory. 
So my current problem is due to STAF or there is something else?

**Comment by mkocabas** [comment]
Yes, it is due to STAF. 

As explained in the [demo readme](https://github.com/mkocabas/VIBE/blob/master/doc/demo.md#flags), there are 2 tracking options `bbox` and `pose`. For pose tracking option, you need to install STAF, and pass the STAF folder to `demo.py` using the `--staf_dir` argument. 

If you don't have STAF installed, you can use the bbox option. You don't need to install anything separately for it.
