### ISSUE TITLE
I got ELS module error while running on a virtual enviroment

### ISSUE THREAD

**Issue by liangwei191** [mkocabas/VIBE#38]
I run the project on the anocanda with python 3.7
I installed the pytorch 1.4.0 and all the requirements but after running the demo,it seems got error
"unable to load egl library ..."
on the line of EGL
I did not know what cause that because this is not really a moudle which can pick by pip.
Should I install cuda or tensorflow or just torch is enough.
Hope give some advice.
Thanks

**Comment by lan786** [comment]
This problem is with pyrender. Pyrender uses EGL or OSMesa as back-end. In my case I tried with OSMesa in windows and it didn't work. EGL with windows is also very tricky. If you are on Ubuntu then install latest Nvidia Driver from run file (most important). Everything will be ok. 
EGL is based on Nvidia but OSMesa is standalone software based.

For more info related to your problem, check this [stackoverflow link](https://stackoverflow.com/questions/60369524/how-to-update-nvidia-driver-safely-in-ubuntu?noredirect=1#comment106791794_60369524)

**Comment by mkocabas** [comment]
Could you check Pyrender docs and github issues? Problem is related to Pyrender installation.

**Comment by liangwei191** [comment]
I can not write replay on github seems so have not reply this.Sorry for that.I tried ubuntu and got the same error but after I googled and installed a ton of libs I solved this.But The win10 based sub system seems not not nvidia device installion.So I failed to get a result even I  sucessfully run the problem.I hope there will be one day a nice anacodna version can be use.Which based on the nvidia card.Thanks.    On Thursday, March 19, 2020, 04:54:08 PM GMT+8, Muhammed Kocabas <notifications@github.com> wrote:  
 
 


Could you check Pyrender docs and github issues? Problem is related to Pyrender installation.
