### ISSUE TITLE
How to save output data in json instead of pkl?

### ISSUE THREAD

**Issue by lan786** [mkocabas/VIBE#49]
Hi @mkocabas , we need a little favor from you that, can you add piece of code to save output data in json file instead of pkl file as an option?

**Comment by athn-nik** [comment]
It is pretty easy do it yourself and the open a pull request and we can merge it.
Something like:
``` import json
with open('vibe_results.json', 'w') as fp:
    json.dump(, fp)
```
should be enough. However json is not so memory efficient. Also ujson package is more efficient than json in my experience.

**Comment by ahsan3803** [comment]
@athn-nik  With this method you can't write JSON file and you will get following error.
`TypeError: Object of type ndarray is not JSON serializable`
because JSON format is quite different and built-in json module can only handle primitives types that have a direct JSON equivalent (lists, dictionary, strings etc.) check following screenshot.

![python_serialize_numpy_array_into_json_explained](https://user-images.githubusercontent.com/40846865/77983611-078df100-7342-11ea-94d2-adf2626b17b9.jpg)

 To get JSON file we need to serialize or encode NumPy array into JSON format. 
 As you know that json module has a JSONEncoder class, we can use this class to encode our NumPy array data into JSON format. 
Here is example that how you can solve it.
```
class NumpyArrayEncode(JSONEncoder):
    def default(self, o):
        if isinstance(o, numpy.ndarray):
            return o.tolist()
        return JSONEncode.default(self, o)

numpyArray = numpy.array(vibe_results)

#then to write data in JSON
json.dump(numpyArray, fp, cls=NumpyArrayEncode)
```
Note: Don't forget to import JSONEncoder from json module
`from json import JSONEncoder`
@lan786 try it. I hope it will solve your problem.

**Comment by ahsan3803** [comment]
@athn-nik   With this method you can't write JSON file and you will get following error.
`TypeError: Object of type ndarray is not JSON serializable`
because JSON format is quite different and built-in json module can only handle primitives types that have a direct JSON equivalent (lists, dictionary, strings etc.) check following screenshot.

![python_serialize_numpy_array_into_json_explained](https://user-images.githubusercontent.com/58796370/77984623-ae738c80-7344-11ea-88cf-01f359374da9.jpg)

 To get JSON file we need to serialize or encode NumPy array into JSON format. 
 As you know that json module has a JSONEncoder class, we can use this class to encode our NumPy array data into JSON format. 
Here is example that how you can solve it.
```
class NumpyArrayEncode(JSONEncoder):
    def default(self, o):
        if isinstance(o, numpy.ndarray):
            return o.tolist()
        return JSONEncode.default(self, o)

numpyArray = numpy.array(vibe_results)

#then to write data in JSON
json.dump(numpyArray, fp, cls=NumpyArrayEncode)
```
Note: Don't forget to import JSONEncoder from json module
`from json import JSONEncoder`
@lan786 try it. I hope it will solve your problem.

**Comment by lan786** [comment]
@ahsan3803  Thanks so much for this solution. I faced same problem as you mention and now I have solved it with your provided example. 
@athn-nik  As I read code and data and it seems that ndarray is different in pkl. In ujson I'm unable to find that how we can encode numpy array as suggested in above solution. I'll submit a new issue in ujson repository.

**Comment by athn-nik** [comment]
Ok, I don't think a pull request is needed for this. If you want you can open one. I am closing this for now. Thanks for the solution @ahsan3803 . Happy to help with more issues @lan786
