### ISSUE TITLE
Question about cam projection.

### ISSUE THREAD

**Issue by jackspp** [mkocabas/VIBE#52]
Hi, mkocabas, thanks for your great work !!!
I have a question about cam projection code: 
https://github.com/mkocabas/VIBE/blob/945fd109eaace037b38c56e22ec235a9d3c5100a/lib/models/spin.py#L426-L439

When i check hmr code,  they assume weak perspective cam, and predict scale and trans(x,y) in camera plane. However, in your code, it seems like that you assume scale(focal_length) is same  all the time, and predict translation from world coordinate to cam coordinate with pred_camera. What is the difference? Could you give a more detailed explanation about `2 * 5000. / (224. * pred_camera[:, 0] + 1e-9)]` ? Thanks !!!

**Comment by mkocabas** [comment]
Hi @jackspp,

Thanks for your interest. The estimated camera is weak perspective, but if you assume a focal length you can convert it to perspective camera. That line is used to convert weak perspective to perspective camera. It is common to assume a fixed focal length to perform perspective projection. We borrowed that part from SPIN implementation.

**Comment by longbowzhang** [comment]
Hi @mkocabas sorry to bother you again.
I have a question about the `pred_camera[:, 1:3]`, which is used later in https://github.com/mkocabas/VIBE/blob/945fd109eaace037b38c56e22ec235a9d3c5100a/lib/models/spin.py#L462 as translation added to points.
Thus I am wondering 
(1) which space are _pred_camera[:, 1:3]_ in? In other words,  why not use _pred_camera[:, 1:3] * _pred_camera[:, 0]_ as the translation[0:2]?
(2) what is the reason behind setting _translation[2] = pred_cam_t[:, 0]_, why move points in the z direction?

**Comment by lvZic** [comment]
> Hi @jackspp,
> 
> Thanks for your interest. The estimated camera is weak perspective, but if you assume a focal length you can convert it to perspective camera. That line is used to convert weak perspective to perspective camera. It is common to assume a fixed focal length to perform perspective projection. We borrowed that part from SPIN implementation.

Hi @mkocabas  sorry to bother you again. 
I found the cam params converge worse, and i use weak perspective in my code, in which kpy_2d = scale(kyp3d[, :2] + txy ). I think the key reason is the focal length of the dataset is different with each image, and it range from 400 mm to 800 mm. So maybe the network cannot regress the scale well? 
As u said "It is common to assume a fixed focal length to perform perspective projection. " . I wonder if the performance would be improved if i use perspective projection instead of weak perspective?
